# Generated by Django 4.0.6 on 2022-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listing_title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
